### ISSUE TITLE
ngx-no-animation-for-dinosaur

### ISSUE THREAD

**Issue by maxisam** [brillout/awesome-angular-components#12]
I created a library that can turn on or turn off animation base on the user agent.

https://www.npmjs.com/package/ngx-no-animation-for-dinosaur

I wonder what category suit better ? Animation ? Utility ?

**Comment by brillout** [comment]
Hey, thanks for opening an issue.

I would say `Miscellaneous` since the problem your are solving is rather uncommon. Is `Miscellaneous` ok for you?

**Comment by maxisam** [comment]
Sounds good to me. It is actually very common if you want to use angular animation. Since the polyfill doesn't support old browsers, we need to turn off animation in runtime only for users using old browsers, otherwise, the whole application doesn't work.

**Comment by Chyngyz** [comment]
Thanks for a handy library, glad to add it.
