### ISSUE TITLE
angular ui components: Element Angular

### ISSUE THREAD

**Issue by WittBulter** [brillout/awesome-angular-components#22]
Here is the link：
[project](https://github.com/eleme/element-angular)
[website](https://element-angular.faas.ele.me/guide/install)

**Comment by mumairofficial** [comment]
I think link was broken here is link for English version: http://element.eleme.io/#/en-US/component/installation

**Comment by brillout** [comment]
Closing as you should use devarchy. Any reason why you didn't use it?
