### ISSUE TITLE
WordPress Api Wrapper

### ISSUE THREAD

**Issue by shprink** [brillout/awesome-angular-components#3]
Not sure where to put it:

https://github.com/shprink/wp-api-angular

**Comment by brillout** [comment]
Salut!
How about `Integrations`?

**Comment by shprink** [comment]
Do you want a PR?

**Comment by brillout** [comment]
A request on [devarchy.com/angular-components](http://devarchy.com/angular-components) would be great. (Easier for me to manage than PRs.)

**Comment by shprink** [comment]
done
