### ISSUE TITLE
Add ncstate-sat/popover

### ISSUE THREAD

**Issue by julianobrasil** [brillout/awesome-angular-components#31]
You could add this component, based on the official [Angular Material 2](https://github.com/angular/material2) Project: https://github.com/ncstate-sat/popover

There's a [demo over here](https://ncstate-sat.github.io/popover/).

**Comment by brillout** [comment]
Is there a reason you didn't use https://devarchy.com/angular to add it?

**Comment by julianobrasil** [comment]
A good reason: I didn't know there was this page to submit it 😄
