### ISSUE TITLE
lots more..

### ISSUE THREAD

**Issue by born2net** [brillout/awesome-angular-components#5]
checkout:
https://github.com/zefoy?utf8=%E2%9C%93&q=ng&type=&language=

**Comment by brillout** [comment]
Neat, I will check them out

**Comment by brillout** [comment]
- [x] reviewed https://github.com/zefoy?utf8=%E2%9C%93&q=ng&type=&language= 
 - [x] reviewed https://github.com/born2net?page=1&q=ng&tab=stars&utf8=%E2%9C%93
 - [x] reviewed https://github.com/born2net?page=1&q=ng&tab=stars&utf8=%E2%9C%93&utf8=%E2%9C%93&q=angular

Lot's of great stuff in there and the catalog is now 192 libs big, thanks a lot!

Wanna co-maintain awesome-angular-components?

**Comment by born2net** [comment]
ya sure... be happy to help maintain it... I am all into ng2+ and follow a number of blogs so I am sure I can keep the list growing.

**Comment by brillout** [comment]
Invite sent

> I am all into ng2+

Yea I kinda figured that out :p 

<br/>

Exciting!

Feel free to push directly on the readme.

**Comment by born2net** [comment]
will do, tx!

**Comment by brillout** [comment]
👍
