### ISSUE TITLE
More stuff

### ISSUE THREAD

**Issue by MurhafSousli** [brillout/awesome-angular-components#6]
Hi, you might want to check these:
https://github.com/MurhafSousli/ng2-sharebuttons
https://github.com/MurhafSousli/ng2-progressbar
https://github.com/MurhafSousli/ng2-disqus

**Comment by brillout** [comment]
ng2-sharebuttons > already in the catalog
ng2-progressbar > neat, I will add it
ng2-disqus > how is your implementation better than https://github.com/Useful-Software-Solutions-Ltd/angular2-disqus ?

**Comment by MurhafSousli** [comment]
@brillout there is comment output developer get add user's comment to his database, and comments count is coming in the next update

**Comment by brillout** [comment]
all 3 libs are now part of the cataog
